In [3]:
import os
import sys
import numpy as np
from PIL import Image
from tqdm import tqdm

### Functions for BundleFusion [dataset](http://graphics.stanford.edu/projects/bundlefusion/)

In [4]:
# rewritting sensorData.h

def make_matrix(data):
    return np.array([np.array(d, dtype=np.float32) for d in data[1:]]).reshape((4, 4))

def read_info(filename):
    header_data = {}
    with open(filename) as file:
        for line in file:
            print(line)
            tmp = line.strip().split('=')
            if 'Intrinsic' in tmp[0] or 'Extrinsic' in tmp[0]:
                header_data[tmp[0].rstrip()] = make_matrix(tmp[-1].rstrip().split(' '))
            else:
                print(tmp[-1])
                header_data[tmp[0].rstrip()] = tmp[-1].strip()
                    
    return header_data
  
def read_image(filename):
    im = Image.open(filename)
    return np.asarray(im)
    
def read_frames(folder, num_frames):
    frames = {'m_colorCompressed': [], 'm_depthCompressed': [], 'm_cameraToWorld': [],
              'm_timeStampColor': [], 'm_timeStampDepth': [], 
              'm_colorSizeBytes': [], 'm_depthSizeBytes': []}
    frames['num_frames'] = num_frames
    for i in range(int(num_frames)):
        frames['m_colorCompressed'].append(read_image(folder + f'/frame-{i:06}.color.jpg'))
        frames['m_timeStampColor'].append(i)
        frames['m_depthCompressed'].append(read_image(folder + f'/frame-{i:06}.depth.png'))
        frames['m_timeStampDepth'].append(i)
        
        frames['m_cameraToWorld'].append(np.loadtxt(folder + f'/frame-{i:06}.pose.txt'))
        h, w, c = frames['m_colorCompressed'][-1].shape
        frames['m_colorSizeBytes'].append(h*w*c) # uint8 * h * w * c 
        h, w = frames['m_depthCompressed'][-1].shape
        frames['m_depthSizeBytes'].append(2*h*w) # uint16 * h * w
    
    return frames

def writeHeaderToFile(out, data):
    # out.write(m_versionNumber, sizeof(unsigned int));
    # #define M_SENSOR_DATA_VERSION 4 (line 800)
    np.array(data['m_versionNumber'], dtype=np.uint32).tofile(out)
    print('m_versionNumber', data['m_versionNumber'])
    print('len(data sensor name)', len(data['m_sensorName'])) 
    np.array([len(data['m_sensorName'])], dtype=np.uint64).tofile(out)
    print('sensor name', data['m_sensorName'].strip())
    out.write(data['m_sensorName'].encode())
    # out.write((const char*)&m_extrinsic, sizeof(mat4f));
    print(data['m_calibrationColorIntrinsic'])
    data['m_calibrationColorIntrinsic'].tofile(out)
    print(data['m_calibrationColorExtrinsic'])
    data['m_calibrationColorExtrinsic'].tofile(out)
    print(data['m_calibrationDepthIntrinsic'])
    data['m_calibrationDepthIntrinsic'].tofile(out)
    print(data['m_calibrationDepthExtrinsic'])
    data['m_calibrationDepthExtrinsic'].tofile(out)
    
#     out.write((const char*)&m_colorCompressionType, sizeof(COMPRESSION_TYPE_COLOR));
#     out.write((const char*)&m_depthCompressionType, sizeof(COMPRESSION_TYPE_DEPTH));
#     m_colorCompressionType, m_depthCompressionType = TYPE_COLOR_UNKNOWN; TYPE_COLOR_UNKNOWN = -1;
    
    # compression type is temporarily set as UNKNOWN 
    np.array([0], dtype=np.int32).tofile(out)
    np.array([0], dtype=np.int32).tofile(out)
    
    np.array(data['m_colorWidth'], dtype=np.uint32).tofile(out)
    np.array(data['m_colorHeight'], dtype=np.uint32).tofile(out)
    np.array(data['m_depthWidth'], dtype=np.uint32).tofile(out)
    np.array(data['m_depthHeight'], dtype=np.uint32).tofile(out)
    np.array(data['m_depthShift'], dtype=np.float32).tofile(out)
    print('depth shift', data['m_depthShift'])

def writeRGBFramesToFile(out, rgbdframes):

    for i in tqdm(range(int(rgbdframes['num_frames']))):
        np.array(rgbdframes['m_cameraToWorld'][i], dtype=np.float32).tofile(out)
        np.array(rgbdframes['m_timeStampColor'][i], dtype=np.uint64).tofile(out)
        np.array(rgbdframes['m_timeStampDepth'][i], dtype=np.uint64).tofile(out)
        np.array(rgbdframes['m_colorSizeBytes'][i], dtype=np.uint64).tofile(out)
        np.array(rgbdframes['m_depthSizeBytes'][i], dtype=np.uint64).tofile(out)
        
        rgbdframes['m_colorCompressed'][i].tofile(out)
        np.array(rgbdframes['m_depthCompressed'][i], dtype=np.uint16).tofile(out)
        #np.array(rgbdframes['m_colorCompressed'][i], dtype=np.ubyte).tofile(out)
        # if i > 100:
        #     break

def writeIMUFramesToFile(out, data):
    '''
        write the following data to the .sens file: (the order matters)
            - number of frames
            - rotationRate
            - acceleration
            - magneticField
            - attitude
            - gravity
            - timeStamp 
        default data:
            num_frames = number of rgbd images in the folder
            IMUFrame() {
                    rotationRate = vec3d(0.0);
                    acceleration = vec3d(0.0);
                    magneticField = vec3d(0.0);
                    attitude = vec3d(0.0);
                    gravity = vec3d(0.0);
                    timeStamp = 0;
                }
            
    '''
    for key in data.keys():
        print(f'writting {key} to file, value = {data[key]}')
        if 'timeStamp' in key:
            np.array(data[key], dtype=np.int64).tofile(out)
        else:
            np.array(data[key], dtype=np.float).tofile(out)
        
def saveToFile(data_dir, filename_out, dir_out='C:/Users/unid0/Downloads/BundleFusion-master/BundleFusion-master/FriedLiver/x64/data'):
    #std::ofstream out(filename, std::ios::binary);
    out = open(f'{dir_out}/{filename_out}.sens', 'wb')

    header_filename = data_dir + '/info.txt'
    print('reading header...')
    data_header = read_info(header_filename)
    print('done!')
    print('reading imu file...')
    imu_filename = data_dir + '/imu.txt'
    imu_data = read_info(imu_filename)
    print('done!')
    #data_header['m_frames.size'] = 100
    imu_data['num_frames'] = data_header['m_frames.size']
    print('reading frames...')
    rgbdframes = read_frames(data_dir, data_header['m_frames.size'])#read rgbframes from data dir
    print('done!')
    
    print('writting header...')
    writeHeaderToFile(out, data_header)
    print('done!')
    print('writting rgbd frames...')
    np.array(int(data_header['m_frames.size']), np.int64).tofile(out)

    writeRGBFramesToFile(out, rgbdframes)
    print('done!')
    print('writting imu frames...')
    writeIMUFramesToFile(out, imu_data)
    print('done!')

In [80]:
saveToFile('./apt0', 'apt0_new')

reading header...
m_versionNumber = 4

 4
m_sensorName = StructureSensor

 StructureSensor
m_colorWidth = 640

 640
m_colorHeight = 480

 480
m_depthWidth = 640

 640
m_depthHeight = 480

 480
m_depthShift = 1000

 1000
m_calibrationColorIntrinsic = 582.871 0 320 0 0 582.871 240 0 0 0 1 0 0 0 0 1 

m_calibrationColorExtrinsic = 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 

m_calibrationDepthIntrinsic = 583 0 320 0 0 583 240 0 0 0 1 0 0 0 0 1 

m_calibrationDepthExtrinsic = 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 

m_frames.size = 8560

 8560
done!
reading imu file...
rotationRate = 0.0

 0.0
acceleration = 0.0

 0.0
magneticField = 0.0

 0.0
attitude = 0.0

 0.0
gravity = 0.0

 0.0
timeStamp = 0
 0
done!
reading frames...
done!
writting header...
m_versionNumber 4
len(data sensor name) 15
senosor name StructureSensor
[[582.871   0.    320.      0.   ]
 [  0.    582.871 240.      0.   ]
 [  0.      0.      1.      0.   ]
 [  0.      0.      0.      1.   ]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 

  1%|          | 89/8560 [00:00<00:09, 883.55it/s]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
BYTES 921600 614400
[[ 9.99998e-01  1.74498e-03 -8.95149e-04 -6.79164e-06]
 [-1.74426e-03  9.99998e-01  7.97849e-04  8.22270e-04]
 [ 8.96555e-04 -7.96269e-04  9.99999e-01 -8.69697e-06]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]
BYTES 921600 614400
[[ 9.99994e-01  3.35404e-03 -6.88818e-04  4.50614e-05]
 [-3.35259e-03  9.99992e-01  2.10069e-03  2.10904e-03]
 [ 6.95841e-04 -2.09837e-03  9.99998e-01  8.12693e-04]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]
BYTES 921600 614400
[[ 9.99940e-01  1.10020e-02  8.58847e-05 -2.03865e-03]
 [-1.10023e-02  9.99881e-01  1.08288e-02  4.77726e-03]
 [ 3.31900e-05 -1.08291e-02  9.99941e-01  1.84944e-03]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]
BYTES 921600 614400
[[ 9.99946e-01  1.03698e-02  2.07547e-04 -2.61505e-03]
 [-1.03715e-02  9.99879e-01  1.16153e-02  4.64777e-03]
 [-8.71570e-05 -1.16169e-02  9.99933e-01  1.80929e-03]
 [ 0.00000e+00  0.00000e+00  0.

  3%|▎         | 278/8560 [00:00<00:08, 926.51it/s]

[[ 0.871663   0.331185  -0.361275  -0.0571494]
 [-0.385635   0.918394  -0.0885348 -0.37056  ]
 [ 0.302471   0.216493   0.928247   0.26475  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.870312   0.332842  -0.363006  -0.0618397]
 [-0.388125   0.917251  -0.0895013 -0.371573 ]
 [ 0.303178   0.218786   0.927478   0.265558 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.867856   0.334742  -0.367116  -0.0712036]
 [-0.392081   0.915289  -0.0922973 -0.374776 ]
 [ 0.305121   0.22404    0.925585   0.26714  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.866597   0.334768  -0.370054  -0.0761612]
 [-0.393316   0.91462   -0.093665  -0.376593 ]
 [ 0.307103   0.226718   0.924277   0.268068 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.862991   0.337479  -0.375972  -0.0849566]
 [-0.398113   0.912424  -0.0948051 -0.378605 ]
 [ 0.311051   0.231495   0.921769   0.271105 ]
 [ 0.         0.       

  6%|▌         | 475/8560 [00:00<00:08, 956.08it/s]

BYTES 921600 614400
[[ 0.998241   0.0368118 -0.0464779 -1.3167   ]
 [-0.0395568  0.997439  -0.05959   -1.40259  ]
 [ 0.0441651  0.0613238  0.99714    1.36411  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.997664   0.0369781 -0.0574459 -1.31763  ]
 [-0.0407692  0.996967  -0.0662876 -1.38933  ]
 [ 0.0548204  0.0684748  0.996145   1.34648  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.997372   0.0394389 -0.0607729 -1.31868  ]
 [-0.0434899  0.996815  -0.0668432 -1.38242  ]
 [ 0.057943   0.0693106  0.995911   1.33758  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.996911   0.0431345 -0.0656294 -1.32039  ]
 [-0.0476758  0.996457  -0.0692791 -1.36689  ]
 [ 0.0624085  0.0721942  0.995436   1.31974  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.996718   0.0447976 -0.0674329 -1.32195  ]
 [-0.0494905  0.996346  -0.0696087 -1.35832  ]
 [ 0.0640681  0.0727176  0.995293   1.311    ]
 [ 

  8%|▊         | 671/8560 [00:00<00:08, 955.18it/s]

[[ 0.48966  -0.355269  0.796252 -1.4431  ]
 [ 0.625129  0.779664 -0.036559 -0.849505]
 [-0.607821  0.515662  0.603859  0.608529]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.486514  -0.362415   0.794959  -1.44428  ]
 [ 0.626525   0.778885  -0.0283458 -0.844402 ]
 [-0.608909   0.511853   0.606001   0.610124 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.485335  -0.366149   0.793968  -1.44475  ]
 [ 0.626858   0.778762  -0.0240481 -0.842509 ]
 [-0.609507   0.509377   0.607484   0.610954 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.483851  -0.370665   0.792777  -1.44577  ]
 [ 0.628422   0.777617  -0.0199645 -0.839495 ]
 [-0.609076   0.507858   0.609185   0.611613 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.482271  -0.375379   0.791521  -1.44493  ]
 [ 0.629665   0.776716  -0.0152957 -0.841179 ]
 [-0.609045   0.50577    0.610951   0.610153 ]
 [ 0.         0.         0.         1. 

 10%|█         | 861/8560 [00:00<00:08, 924.70it/s]

BYTES 921600 614400
[[ 0.378941  -0.260488   0.888003  -1.23479  ]
 [ 0.621078   0.782951  -0.0353631 -0.861561 ]
 [-0.68605    0.56492    0.458476   0.445393 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.398989  -0.277145   0.87407   -1.21995  ]
 [ 0.621461   0.782639  -0.0355256 -0.850399 ]
 [-0.674235   0.557375   0.4845     0.450103 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.411948  -0.281854   0.86652   -1.21192  ]
 [ 0.621097   0.782677  -0.0406906 -0.845534 ]
 [-0.666736   0.554955   0.497481   0.450861 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.437241  -0.28981    0.85137   -1.19704  ]
 [ 0.619709   0.783128  -0.0516859 -0.837686 ]
 [-0.651752   0.550201   0.522013   0.453234 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.448106  -0.295437   0.843752  -1.18945  ]
 [ 0.618691   0.783766  -0.0541463 -0.832404 ]
 [-0.645308   0.546286   0.533995   0.454367 ]
 [ 

 11%|█         | 954/8560 [00:01<00:08, 913.33it/s]

[[ 0.783663   0.383894  -0.488363  -0.175162 ]
 [-0.425261   0.904616   0.0286971 -0.516648 ]
 [ 0.452797   0.185193   0.872169   0.280822 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.792331   0.379841  -0.477424  -0.163821 ]
 [-0.419744   0.907291   0.0252402 -0.50042  ]
 [ 0.44275    0.180397   0.878311   0.271321 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.80547    0.37484   -0.459034  -0.15601  ]
 [-0.411615   0.911099   0.0217262 -0.492838 ]
 [ 0.42637    0.171446   0.888153   0.261262 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.820111    0.362291   -0.442903   -0.149487  ]
 [-0.400734    0.916165    0.00738765 -0.481277  ]
 [ 0.408448    0.171428    0.896539    0.249771  ]
 [ 0.          0.          0.          1.        ]]
BYTES 921600 614400
[[ 8.27508e-01  3.58579e-01 -4.32031e-01 -1.45446e-01]
 [-3.97335e-01  9.17673e-01  6.01707e-04 -4.73935e-01]
 [ 3.96679e-01  1.71163e-01  9.01858e-

 13%|█▎        | 1137/8560 [00:01<00:08, 901.14it/s]

BYTES 921600 614400
[[ 0.988452   0.0752805 -0.13151    0.177867 ]
 [-0.110911   0.950768  -0.289377  -0.734109 ]
 [ 0.103251   0.300621   0.948138   0.497973 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.988342   0.0793911 -0.129911   0.177678 ]
 [-0.114144   0.95105   -0.287184  -0.715292 ]
 [ 0.100752   0.298665   0.949025   0.482376 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.988941   0.0850783 -0.12148    0.171535 ]
 [-0.117278   0.949994  -0.289407  -0.696606 ]
 [ 0.0907828  0.300453   0.949466   0.477872 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.989716   0.0823504 -0.116964   0.168459 ]
 [-0.112815   0.952081  -0.28428   -0.680188 ]
 [ 0.0879488  0.294551   0.95158    0.464978 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.989603   0.0824226 -0.117863   0.167124 ]
 [-0.112952   0.952703  -0.282134  -0.672592 ]
 [ 0.0890345  0.292514   0.952108   0.458352 ]
 [ 

 15%|█▌        | 1318/8560 [00:01<00:08, 893.79it/s]

BYTES 921600 614400
[[ 0.930897  -0.185649   0.314589   0.0422784]
 [ 0.204495   0.978476  -0.0276887  0.762829 ]
 [-0.302677   0.0901073  0.948824  -0.991985 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.931445  -0.184373   0.313713   0.0400658]
 [ 0.203553   0.978628  -0.029218   0.772537 ]
 [-0.301621   0.0910724  0.949068  -0.999521 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.930604  -0.185498   0.315543   0.0368829]
 [ 0.204122   0.978581  -0.0267217  0.78192  ]
 [-0.303828   0.0892768  0.948535  -1.00694  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.930081  -0.187188   0.316085   0.0365948]
 [ 0.205671   0.97828   -0.025842   0.786602 ]
 [-0.304382   0.0890447  0.948379  -1.01096  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.928638  -0.191507   0.317736   0.0354481]
 [ 0.209882   0.977425  -0.0243008  0.795851 ]
 [-0.305909   0.0892538  0.947868  -1.01781  ]
 [ 

 18%|█▊        | 1499/8560 [00:01<00:07, 894.74it/s]

[[-0.696556  -0.359055   0.621199   0.480047 ]
 [ 0.584551   0.218063   0.781504  -0.0119674]
 [-0.416063   0.907484   0.0579925 -0.0907268]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.713134  -0.341685   0.61212    0.477885 ]
 [ 0.575199   0.21394    0.789541  -0.0226519]
 [-0.400731   0.91514    0.0439693 -0.0866378]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.723816  -0.331081   0.605372   0.475487 ]
 [ 0.568485   0.211081   0.795153  -0.0268868]
 [-0.391043   0.91969    0.0354311 -0.0834759]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.732836  -0.319415   0.60077    0.472396 ]
 [ 0.563105   0.210898   0.799021  -0.0313855]
 [-0.381921   0.923848   0.0253106 -0.0805141]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.750506   -0.304867    0.586342    0.467337  ]
 [ 0.547748    0.209439    0.810004   -0.0407294 ]
 [-0.369747    0.929081    0.00980531 -0.0773778 ]
 [ 0.      

 20%|█▉        | 1679/8560 [00:01<00:07, 890.41it/s]

BYTES 921600 614400
[[-0.909749 -0.171371  0.378137  0.316699]
 [ 0.31174   0.319546  0.894823  1.01533 ]
 [-0.274179  0.931946 -0.237283 -1.36074 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.910703 -0.170185  0.376374  0.316587]
 [ 0.30981   0.321232  0.89489   1.01227 ]
 [-0.2732    0.931583 -0.239822 -1.35828 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.911475 -0.171798  0.373764  0.316467]
 [ 0.307047  0.320515  0.896099  1.00761 ]
 [-0.273745  0.931534 -0.239391 -1.35573 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.913329 -0.167399  0.371224  0.316854]
 [ 0.303719  0.32723   0.894805  0.999931]
 [-0.271265  0.929999 -0.248027 -1.35161 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.915221 -0.165431  0.367428  0.316523]
 [ 0.299323  0.331352  0.894769  0.996274]
 [-0.269771  0.928891 -0.253744 -1.34826 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.919382 -0.

 22%|██▏       | 1861/8560 [00:02<00:07, 895.08it/s]

[[-0.984178  -0.0430306  0.171879   0.146747 ]
 [ 0.158471   0.220129   0.962512  -0.862053 ]
 [-0.079253   0.974521  -0.209827   0.491827 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.983972  -0.0436164  0.172907   0.149165 ]
 [ 0.159299   0.220776   0.962228  -0.865795 ]
 [-0.0801424  0.974349  -0.210289   0.495451 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.985483  -0.0411266  0.16472    0.154012 ]
 [ 0.152188   0.216049   0.964449  -0.874944 ]
 [-0.0752521  0.975516  -0.206654   0.497027 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.98643   -0.0390198  0.159481   0.155893 ]
 [ 0.147397   0.217419   0.964885  -0.876427 ]
 [-0.0723238  0.975298  -0.208717   0.501431 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.987779  -0.0291012  0.153123   0.159416 ]
 [ 0.14329    0.217025   0.965592  -0.880573 ]
 [-0.0613314  0.975732  -0.210203   0.507898 ]
 [ 0.         0.       

 23%|██▎       | 1951/8560 [00:02<00:07, 894.58it/s]

[[-0.800844  -0.28929    0.524367   0.215102 ]
 [ 0.469032   0.241447   0.849537  -0.164684 ]
 [-0.372369   0.926291  -0.0576757  0.0227511]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.791143  -0.308418   0.528178   0.222305 ]
 [ 0.476414   0.230813   0.848384  -0.1597   ]
 [-0.383567   0.922824  -0.0356716  0.0262924]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.787252  -0.316187   0.529397   0.225122 ]
 [ 0.477497   0.230637   0.847823  -0.158332 ]
 [-0.390169   0.920235  -0.0305917  0.0291717]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.783945  -0.330704   0.525418   0.229229 ]
 [ 0.475176   0.225042   0.850626  -0.156427 ]
 [-0.399547   0.91651   -0.0192781  0.0329955]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.783306  -0.334874   0.523728   0.230032 ]
 [ 0.474947   0.221172   0.851767  -0.155472 ]
 [-0.401069   0.915938  -0.014198   0.0349881]
 [ 0.         0.       

 25%|██▍       | 2134/8560 [00:02<00:07, 898.50it/s]

BYTES 921600 614400
[[-0.712346  -0.22742    0.66396   -0.0820212]
 [ 0.506676   0.48798    0.710743   0.775608 ]
 [-0.485636   0.842708  -0.232382  -1.204    ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.720337  -0.222072   0.657114  -0.0889016]
 [ 0.502417   0.486106   0.715037   0.780268 ]
 [-0.478217   0.845213  -0.238588  -1.20754  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.725446  -0.219309   0.652404  -0.0924094]
 [ 0.499941   0.483586   0.718473   0.783028 ]
 [-0.473061   0.847377  -0.241174  -1.20955  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.734812  -0.215627   0.643083  -0.0990868]
 [ 0.495196   0.477353   0.725889   0.788589 ]
 [-0.463499   0.851844  -0.243988  -1.2127   ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.738534 -0.214883  0.639056 -0.102509]
 [ 0.493926  0.472731  0.729769  0.79164 ]
 [-0.458916  0.854606 -0.242991 -1.21465 ]
 [ 0.        0.

 27%|██▋       | 2314/8560 [00:02<00:07, 888.91it/s]

[[-0.528749  -0.375204   0.761345  -2.1047   ]
 [ 0.565322   0.513401   0.645625   0.472192 ]
 [-0.633116   0.771778  -0.0593489 -0.773868 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.530187  -0.372211   0.761814  -2.11302  ]
 [ 0.563467   0.516712   0.644604   0.473682 ]
 [-0.633567   0.771018  -0.0642252 -0.77142  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.537081  -0.370631   0.757745  -2.12063  ]
 [ 0.56084    0.514094   0.648973   0.471559 ]
 [-0.630081   0.773524  -0.0682453 -0.770618 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.542541  -0.369309   0.754493  -2.12858  ]
 [ 0.561416   0.50871    0.652707   0.47157  ]
 [-0.624869   0.777705  -0.0686603 -0.769814 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.544595  -0.368365   0.753475  -2.13231  ]
 [ 0.562027   0.506545   0.653864   0.471927 ]
 [-0.622529   0.779563  -0.0688309 -0.768831 ]
 [ 0.         0.       

 29%|██▉       | 2495/8560 [00:02<00:06, 893.18it/s]

BYTES 921600 614400
[[-0.900329 -0.188582  0.39223  -2.63818 ]
 [ 0.259533  0.490811  0.831713  0.131747]
 [-0.349357  0.850612 -0.392948 -0.498735]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.897596 -0.180893  0.401995 -2.64776 ]
 [ 0.270506  0.494016  0.826302  0.129447]
 [-0.348065  0.850427 -0.394494 -0.494644]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.893298 -0.171675  0.415387 -2.66374 ]
 [ 0.284415  0.499711  0.818167  0.118517]
 [-0.348032  0.849009 -0.397564 -0.488377]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.890453 -0.16999   0.422135 -2.6736  ]
 [ 0.290767  0.501047  0.815111  0.114694]
 [-0.350071  0.848561 -0.396731 -0.484091]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.884424 -0.169666  0.43475  -2.69098 ]
 [ 0.299986  0.506927  0.808105  0.103466]
 [-0.357495  0.845126 -0.397441 -0.474897]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.877706  -0

 31%|███       | 2674/8560 [00:02<00:06, 884.81it/s]

 921600 614400
[[-0.579459 -0.203516  0.789182 -3.15527 ]
 [ 0.484815  0.692285  0.534505 -0.221769]
 [-0.65512   0.692331 -0.302483 -0.158047]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.575889 -0.204652  0.791498 -3.15389 ]
 [ 0.485075  0.693782  0.532324 -0.224481]
 [-0.658068  0.690495 -0.30027  -0.155751]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.572337 -0.203606  0.794339 -3.15252 ]
 [ 0.487481  0.694453  0.529243 -0.225167]
 [-0.659388  0.69013  -0.298207 -0.152825]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.569966 -0.203705  0.796017 -3.15186 ]
 [ 0.489103  0.694338  0.527895 -0.225943]
 [-0.660239  0.690217 -0.296116 -0.152256]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.567295 -0.204692  0.79767  -3.15083 ]
 [ 0.490164  0.694423  0.526798 -0.226512]
 [-0.661751  0.689839 -0.29361  -0.150264]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.561124 -0.20806

 33%|███▎      | 2852/8560 [00:03<00:06, 879.04it/s]

BYTES 921600 614400
[[-0.536804  -0.364551   0.760884  -1.28871  ]
 [ 0.552836   0.529279   0.643612   0.828777 ]
 [-0.637349   0.766137  -0.0825815 -1.15368  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.524128  -0.363212   0.770303  -1.2657   ]
 [ 0.563683   0.530066   0.633475   0.838262 ]
 [-0.638397   0.766229  -0.0730858 -1.16793  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.500219  -0.357256   0.788764  -1.24623  ]
 [ 0.580717   0.537284   0.611632   0.843824 ]
 [-0.642299   0.763999  -0.0612952 -1.18489  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.487287  -0.349574   0.800218  -1.2409   ]
 [ 0.587487   0.54675    0.596593   0.848755 ]
 [-0.646073   0.760829  -0.0610535 -1.18945  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.475682  -0.345924   0.808742  -1.23107  ]
 [ 0.591752   0.554416   0.585194   0.852824 ]
 [-0.650812   0.756941  -0.0590247 -1.19507  ]
 [ 

 35%|███▌      | 3028/8560 [00:03<00:06, 876.09it/s]

BYTES 921600 614400
[[ 0.399309 -0.479539  0.781406 -0.394849]
 [ 0.595466  0.783715  0.176665  0.770035]
 [-0.697117  0.394757  0.598494 -1.01876 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.392807 -0.478233  0.785491 -0.404003]
 [ 0.595447  0.783186  0.179059  0.772884]
 [-0.700817  0.397382  0.592404 -1.02455 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.392088 -0.475459  0.787531 -0.41415 ]
 [ 0.594121  0.784475  0.177818  0.774517]
 [-0.702343  0.398169  0.590064 -1.02912 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.38902  -0.475097  0.789269 -0.420336]
 [ 0.594508  0.783943  0.178867  0.77363 ]
 [-0.703721  0.399644  0.587419 -1.02966 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.387541 -0.47338   0.791027 -0.430579]
 [ 0.593971  0.784447  0.178443  0.776299]
 [-0.704989  0.400693  0.58518  -1.03466 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.384321 -0.

 36%|███▋      | 3116/8560 [00:03<00:06, 857.59it/s]

[[ 0.217838 -0.446822  0.867696 -2.01468 ]
 [ 0.66106   0.721606  0.205631  0.819288]
 [-0.718015  0.528805  0.45257  -1.10185 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.224042 -0.446348  0.866359 -2.01694 ]
 [ 0.658526  0.724649  0.203044  0.82193 ]
 [-0.718435  0.52503   0.456283 -1.10426 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.229633 -0.446619  0.864754 -2.02271 ]
 [ 0.656769  0.726817  0.200976  0.825351]
 [-0.718278  0.521793  0.460227 -1.10859 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.232733 -0.446447  0.864014 -2.02545 ]
 [ 0.65696   0.727239  0.198814  0.8255  ]
 [-0.717105  0.521352  0.46255  -1.11093 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.24086  -0.442173  0.863984 -2.03261 ]
 [ 0.656323  0.729999  0.190634  0.82837 ]
 [-0.715001  0.521137  0.466036 -1.11407 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.246641 -0.441295  0.862802 -2.

 38%|███▊      | 3291/8560 [00:03<00:06, 857.69it/s]

BYTES 921600 614400
[[ 0.238079 -0.58363   0.776334 -1.67995 ]
 [ 0.659057  0.684207  0.312257  0.841957]
 [-0.713416  0.437307  0.54754  -1.02231 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.239615 -0.580128  0.778483 -1.70174 ]
 [ 0.657367  0.687019  0.309633  0.844801]
 [-0.71446   0.437556  0.545977 -1.02844 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.239776 -0.577368  0.780483 -1.71526 ]
 [ 0.654759  0.689747  0.309093  0.845688]
 [-0.716797  0.436916  0.543422 -1.0307  ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.239549 -0.57414   0.78293  -1.73459 ]
 [ 0.652517  0.692332  0.308055  0.846055]
 [-0.718915  0.437081  0.540483 -1.03807 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.241528 -0.569319  0.785837 -1.74855 ]
 [ 0.653347  0.69417   0.302102  0.8472  ]
 [-0.717497  0.440458  0.539625 -1.03934 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.25369  -0.

 41%|████      | 3468/8560 [00:03<00:05, 860.75it/s]

[[ 0.790729  -0.354571   0.499025  -2.56372  ]
 [ 0.388461   0.920655   0.0386163  0.891524 ]
 [-0.473123   0.163317   0.865727  -1.16432  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.796301  -0.355855   0.489154  -2.56634  ]
 [ 0.388474   0.9207     0.0373984  0.895549 ]
 [-0.463673   0.160243   0.871395  -1.16274  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.799887  -0.356515   0.482782  -2.56761  ]
 [ 0.387953   0.920924   0.0372937  0.89591  ]
 [-0.457901   0.157466   0.874946  -1.16264  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.807326  -0.35657    0.470193  -2.57132  ]
 [ 0.385787   0.921858   0.0366891  0.897483 ]
 [-0.446534   0.151775   0.8818    -1.16114  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.811306  -0.354488   0.464887  -2.57379  ]
 [ 0.382493   0.923238   0.0364771  0.898443 ]
 [-0.442132   0.148222   0.884618  -1.16008  ]
 [ 0.         0.       

 43%|████▎     | 3642/8560 [00:04<00:05, 858.19it/s]

[[ 0.680757 -0.18461   0.708865 -3.08782 ]
 [ 0.45171   0.867616 -0.207845  0.878938]
 [-0.576652  0.461693  0.674026 -1.33579 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.680328 -0.177411  0.711111 -3.09238 ]
 [ 0.447652  0.868832 -0.211513  0.876505]
 [-0.580311  0.462229  0.670509 -1.33513 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.678947 -0.168663  0.714551 -3.09332 ]
 [ 0.441069  0.871752 -0.213323  0.874283]
 [-0.586931  0.460002  0.666266 -1.33742 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.67825  -0.165132  0.716036 -3.09292 ]
 [ 0.438708  0.872705 -0.214293  0.87303 ]
 [-0.589501  0.459475  0.664357 -1.33989 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.675805 -0.160175  0.719466 -3.0933  ]
 [ 0.437263  0.872912 -0.21639   0.871058]
 [-0.59337   0.460834  0.659957 -1.34131 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.677455 -0.156432  0.718737 -3.

 45%|████▍     | 3821/8560 [00:04<00:05, 874.04it/s]

[[ 0.996781   -0.0215445   0.0772174  -2.51092   ]
 [ 0.0209383   0.999743    0.00865195  0.335924  ]
 [-0.077384   -0.00700727  0.996977   -0.467978  ]
 [ 0.          0.          0.          1.        ]]
BYTES 921600 614400
[[ 0.996801   -0.0292296   0.0743803  -2.51282   ]
 [ 0.0287863   0.999561    0.00702556  0.335569  ]
 [-0.074553   -0.00486196  0.997205   -0.462938  ]
 [ 0.          0.          0.          1.        ]]
BYTES 921600 614400
[[ 0.997929   -0.032953    0.055243   -2.51028   ]
 [ 0.0327217   0.999451    0.00508603  0.31905   ]
 [-0.0553803  -0.00326784  0.99846    -0.451597  ]
 [ 0.          0.          0.          1.        ]]
BYTES 921600 614400
[[ 9.98362e-01 -3.58729e-02  4.45765e-02 -2.50548e+00]
 [ 3.57980e-02  9.99356e-01  2.47729e-03  3.06098e-01]
 [-4.46366e-02 -8.77484e-04  9.99003e-01 -4.39951e-01]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]
BYTES 921600 614400
[[ 9.98381e-01 -3.73123e-02  4.29348e-02 -2.50407e+00]
 [ 3.72523e-02  9.99303e-01  

 47%|████▋     | 3996/8560 [00:04<00:05, 862.13it/s]

BYTES 921600 614400
[[-0.221764  -0.493274   0.841131  -1.66608  ]
 [ 0.62536    0.589905   0.51082   -0.233544 ]
 [-0.748161   0.639292   0.177654   0.0501032]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.221978  -0.500216   0.836965  -1.6576   ]
 [ 0.62652    0.584556   0.515526  -0.236487 ]
 [-0.747127   0.63881    0.183637   0.0514264]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.219733  -0.505229   0.834542  -1.65124  ]
 [ 0.623996   0.584782   0.518323  -0.238331 ]
 [-0.749897   0.634644   0.186765   0.0552667]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.224785  -0.500843   0.83584   -1.63887  ]
 [ 0.608216   0.598051   0.521927  -0.241195 ]
 [-0.761278   0.625692   0.170188   0.0640477]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.24905   -0.4997     0.829623  -1.62374  ]
 [ 0.600033   0.59279    0.537178  -0.246952 ]
 [-0.76022    0.631585   0.152202   0.0725465]
 [ 

 48%|████▊     | 4085/8560 [00:04<00:05, 868.49it/s]

[[-0.746965  -0.4221     0.513687  -1.84286  ]
 [ 0.476912   0.198163   0.856321  -0.978958 ]
 [-0.463247   0.884626   0.0532839  0.93648  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.741586  -0.429701   0.515177  -1.83925  ]
 [ 0.477222   0.201829   0.855292  -0.969261 ]
 [-0.471498   0.880126   0.0553896  0.939138 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.739249  -0.434381   0.51461   -1.83625  ]
 [ 0.478433   0.19902    0.855273  -0.964804 ]
 [-0.473932   0.878467   0.0606973  0.936392 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.736422  -0.438165   0.515454  -1.83534  ]
 [ 0.480547   0.197503   0.854439  -0.960048 ]
 [-0.476189   0.876929   0.0651131  0.934308 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.731686  -0.44446    0.516809  -1.83008  ]
 [ 0.487483   0.188743   0.852488  -0.950005 ]
 [-0.476441   0.875689   0.0785667  0.922946 ]
 [ 0.         0.       

 50%|████▉     | 4263/8560 [00:04<00:04, 870.09it/s]

[[ 0.279672  -0.159404   0.94677   -1.57526  ]
 [ 0.656466   0.751337  -0.0674176 -1.05742  ]
 [-0.700597   0.640377   0.314772   0.648271 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.279335  -0.155941   0.947446  -1.57504  ]
 [ 0.656434   0.751138  -0.0699057 -1.05857  ]
 [-0.700761   0.641463   0.312184   0.64713  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.275489  -0.151811   0.949242  -1.57302  ]
 [ 0.65755    0.75007   -0.0708764 -1.06241  ]
 [-0.701238   0.643699   0.306459   0.642468 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.268118 -0.146767  0.952141 -1.57286 ]
 [ 0.657465  0.750274 -0.069488 -1.06436 ]
 [-0.704168  0.64463   0.297656  0.640655]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.266245  -0.14457    0.953002  -1.57179  ]
 [ 0.658283   0.74949   -0.0702108 -1.06451  ]
 [-0.704115   0.646038   0.294716   0.637379 ]
 [ 0.         0.         0.         1. 

 52%|█████▏    | 4440/8560 [00:05<00:04, 874.86it/s]

BYTES 921600 614400
[[ 0.90568   -0.319283   0.278931  -1.13946  ]
 [ 0.329028   0.944238   0.0124956 -0.336919 ]
 [-0.267367   0.0804593  0.96023    0.333897 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.907734  -0.315182   0.27691   -1.14248  ]
 [ 0.324497   0.9458     0.0127931 -0.340151 ]
 [-0.265934   0.078244   0.96081    0.335871 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.908444  -0.313159   0.276875  -1.14438  ]
 [ 0.322597   0.94646    0.0120306 -0.340462 ]
 [-0.265819   0.0783902  0.960831   0.337254 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.909225  -0.310355   0.277468  -1.14601  ]
 [ 0.319394   0.94753    0.0132262 -0.342271 ]
 [-0.267014   0.0765962  0.960644   0.339137 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.909289  -0.307544   0.280375  -1.15023  ]
 [ 0.315229   0.948836   0.0184579 -0.349031 ]
 [-0.271707   0.0715988  0.959713   0.34368  ]
 [ 

 54%|█████▍    | 4619/8560 [00:05<00:04, 878.69it/s]

[[-0.712398 -0.315742  0.626734 -0.583888]
 [ 0.46644   0.454217  0.759026 -0.772317]
 [-0.52433   0.833062 -0.176308  0.674985]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.724873 -0.30778   0.616303 -0.556471]
 [ 0.457465  0.453833  0.764697 -0.762347]
 [-0.515057  0.836246 -0.188172  0.660811]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.741929 -0.301124  0.599054 -0.526618]
 [ 0.448885  0.440595  0.777417 -0.753627]
 [-0.498039  0.845695 -0.19172   0.645188]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.746481 -0.300329  0.593774 -0.514796]
 [ 0.442438  0.44249   0.780033 -0.748287]
 [-0.497006  0.844988 -0.197433  0.63986 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.770425 -0.284308  0.570625 -0.487287]
 [ 0.428967  0.430961  0.793889 -0.739049]
 [-0.471626  0.856412 -0.210064  0.624997]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.779025 -0.277654  0.562163 -0.

 56%|█████▌    | 4797/8560 [00:05<00:04, 879.19it/s]

[[-0.743274  -0.473429   0.472661  -1.35078  ]
 [ 0.506334   0.0636554  0.859985  -1.39107  ]
 [-0.437229   0.878529   0.1924     1.33893  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.744218 -0.472571  0.472034 -1.35672 ]
 [ 0.504486  0.065476  0.860933 -1.39199 ]
 [-0.437759  0.878857  0.189677  1.33874 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.745873  -0.47294    0.469043  -1.37048  ]
 [ 0.499156   0.0693943  0.863729  -1.392    ]
 [-0.441041   0.878358   0.184312   1.34181  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.74673   -0.476036   0.464525  -1.3824   ]
 [ 0.493358   0.0719798  0.866843  -1.39159  ]
 [-0.446084   0.876475   0.181107   1.34207  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.745823  -0.47747    0.46451   -1.39339  ]
 [ 0.49355    0.0722463  0.866712  -1.38792  ]
 [-0.447388   0.875673   0.181772   1.33993  ]
 [ 0.         0.         0.         1. 

 58%|█████▊    | 4974/8560 [00:05<00:04, 870.31it/s]

BYTES 921600 614400
[[-0.926045 -0.150393  0.346154 -2.01005 ]
 [ 0.223775  0.51977   0.824478 -1.15483 ]
 [-0.303916  0.840964 -0.447676  0.71246 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.927425 -0.151818  0.341808 -2.00989 ]
 [ 0.221713  0.512843  0.829359 -1.15209 ]
 [-0.301206  0.844952 -0.441963  0.713317]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.931262 -0.152378  0.330954 -2.0082  ]
 [ 0.21686   0.498111  0.839557 -1.14649 ]
 [-0.292782  0.853619 -0.430827  0.715764]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.932521 -0.15892   0.324266 -2.00362 ]
 [ 0.211742  0.486762  0.847484 -1.14732 ]
 [-0.292522  0.858957 -0.420265  0.709183]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.935263 -0.163262  0.314052 -2.00332 ]
 [ 0.205865  0.470854  0.857856 -1.14037 ]
 [-0.287928  0.866973 -0.406762  0.713571]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.937373 -0.

 59%|█████▉    | 5065/8560 [00:05<00:03, 880.14it/s]

BYTES 921600 614400
[[-0.737569   0.293505  -0.60815   -2.43561  ]
 [-0.537714   0.289505   0.791865  -1.25751  ]
 [ 0.408479   0.911066  -0.0557075  1.05563  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.738308   0.286786  -0.610454  -2.4365   ]
 [-0.538441   0.294451   0.789544  -1.26008  ]
 [ 0.406179   0.911621  -0.0629781  1.05148  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.738445   0.280014  -0.613425  -2.43768  ]
 [-0.53965    0.300056   0.786603  -1.26306  ]
 [ 0.404322   0.911898  -0.0704646  1.0474   ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.738472   0.271754  -0.617097  -2.43744  ]
 [-0.54103    0.307394   0.782813  -1.26526  ]
 [ 0.402424   0.911953  -0.0799746  1.04343  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.738536   0.268668  -0.618371  -2.43745  ]
 [-0.541543   0.309954   0.781447  -1.26594  ]
 [ 0.401616   0.912001  -0.0834167  1.04092  ]
 [ 

 61%|██████▏   | 5252/8560 [00:05<00:03, 901.71it/s]

BYTES 921600 614400
[[-0.760306  0.252386 -0.598528 -2.71458 ]
 [-0.510588  0.337388  0.790866 -0.874046]
 [ 0.40154   0.906902 -0.127653  0.572636]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.763602  0.251071 -0.594875 -2.70911 ]
 [-0.507663  0.335848  0.793401 -0.875104]
 [ 0.398988  0.907838 -0.128994  0.574916]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.76531   0.249358 -0.593399 -2.70553 ]
 [-0.506567  0.335431  0.794277 -0.875293]
 [ 0.397103  0.908464 -0.130392  0.577589]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.769564  0.247725 -0.588561 -2.69802 ]
 [-0.503744  0.330931  0.797952 -0.875931]
 [ 0.392446  0.910559 -0.129882  0.581232]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.77466   0.245698 -0.582696 -2.69014 ]
 [-0.499215  0.328021  0.801989 -0.878256]
 [ 0.388183  0.91216  -0.131448  0.587466]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.775236  0.

 64%|██████▎   | 5445/8560 [00:06<00:03, 931.66it/s]

BYTES 921600 614400
[[-0.181188  0.404895 -0.896231 -2.41277 ]
 [-0.715992  0.570426  0.402454 -0.106003]
 [ 0.674186  0.714615  0.186548 -0.140078]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.182709  0.391398 -0.901901 -2.42124 ]
 [-0.714125  0.577679  0.395364 -0.110553]
 [ 0.675754  0.716307  0.17396  -0.115668]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.160374  0.389084 -0.907135 -2.42943 ]
 [-0.715633  0.587131  0.378347 -0.111284]
 [ 0.679816  0.709853  0.184281 -0.117943]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.150082  0.388688 -0.909064 -2.43431 ]
 [-0.714197  0.593194  0.371542 -0.114608]
 [ 0.683665  0.705013  0.188572 -0.119363]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.133925  0.380655 -0.914967 -2.44098 ]
 [-0.711188  0.606059  0.356237 -0.118878]
 [ 0.690127  0.698423  0.189551 -0.123178]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.118319  0.

 66%|██████▌   | 5634/8560 [00:06<00:03, 934.52it/s]

BYTES 921600 614400
[[-0.958403  0.182275 -0.219636 -2.66513 ]
 [-0.172303  0.243992  0.954348  0.205991]
 [ 0.227543  0.952493 -0.202435 -0.388877]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.959832  0.182533 -0.213082 -2.66404 ]
 [-0.166039  0.242657  0.955797  0.20836 ]
 [ 0.22617   0.952785 -0.202603 -0.395747]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.962391  0.179613 -0.203821 -2.66856 ]
 [-0.157024  0.244467  0.956859  0.216696]
 [ 0.221692  0.952877 -0.207069 -0.402554]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.964283  0.177749 -0.196375 -2.67167 ]
 [-0.149992  0.244625  0.957946  0.220041]
 [ 0.218312  0.953186 -0.209227 -0.406791]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.967385  0.172724 -0.185291 -2.67615 ]
 [-0.139273  0.248326  0.958612  0.230743]
 [ 0.211588  0.953153 -0.216171 -0.415824]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.968711  0.

 68%|██████▊   | 5822/8560 [00:06<00:02, 933.64it/s]

BYTES 921600 614400
[[-0.813283 -0.223284  0.537322 -2.65111 ]
 [ 0.342945  0.562065  0.752643  0.226442]
 [-0.470063  0.796384 -0.380543 -0.608213]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.810712 -0.224868  0.540537 -2.64785 ]
 [ 0.346607  0.559732  0.752704  0.227837]
 [-0.471815  0.79758  -0.375841 -0.605576]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.807086 -0.231332  0.543229 -2.63943 ]
 [ 0.348858  0.555443  0.754839  0.229061]
 [-0.476351  0.79873  -0.367588 -0.600926]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.805802 -0.23609   0.543088 -2.63524 ]
 [ 0.348402  0.552574  0.757151  0.229296]
 [-0.478852  0.799327 -0.36301  -0.599245]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.804181 -0.244013  0.541988 -2.6266  ]
 [ 0.347422  0.546893  0.761712  0.231584]
 [-0.482277  0.800853 -0.355025 -0.594254]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.802282 -0.

 70%|███████   | 6015/8560 [00:06<00:02, 948.29it/s]

[[-0.658509 -0.314929  0.68351  -1.42033 ]
 [ 0.449049  0.564407  0.692676  0.549253]
 [-0.603921  0.763063 -0.230248 -0.996671]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.654578 -0.317003  0.686321 -1.41755 ]
 [ 0.453671  0.56149   0.692034  0.551465]
 [-0.604739  0.764355 -0.223724 -0.996646]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.647853 -0.32155   0.690574 -1.4099  ]
 [ 0.460653  0.556638  0.691341  0.557336]
 [-0.6067    0.766002 -0.212497 -0.994666]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.642471 -0.329061  0.692061 -1.40432 ]
 [ 0.464609  0.550923  0.693269  0.563149]
 [-0.6094    0.766944 -0.201067 -0.993725]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.639828 -0.33399   0.692149 -1.40006 ]
 [ 0.470222  0.542235  0.696328  0.565513]
 [-0.607874  0.770994 -0.189888 -0.999273]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.637764 -0.33565   0.69325  -1.

 72%|███████▏  | 6205/8560 [00:06<00:02, 933.93it/s]

BYTES 921600 614400
[[-0.862325  0.249048 -0.440875 -3.36118 ]
 [-0.364469  0.299138  0.881861  0.310904]
 [ 0.351508  0.921136 -0.167184 -1.04236 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.860294  0.251372 -0.443516 -3.36597 ]
 [-0.3691    0.292982  0.882001  0.316655]
 [ 0.351652  0.922482 -0.159269 -1.05073 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.857846  0.256184 -0.445499 -3.37453 ]
 [-0.370567  0.292262  0.881625  0.326359]
 [ 0.35606   0.921386 -0.155783 -1.06723 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.853184  0.262661 -0.450651 -3.38267 ]
 [-0.380251  0.278201  0.882051  0.331567]
 [ 0.357052  0.923912 -0.137479 -1.09125 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.848678  0.275175 -0.45169  -3.39355 ]
 [-0.385854  0.261981  0.884581  0.34376 ]
 [ 0.361749  0.925011 -0.11616  -1.10577 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.847945  0.

 74%|███████▎  | 6299/8560 [00:07<00:02, 933.70it/s]

BYTES 921600 614400
[[-0.638333  0.526414 -0.561621 -3.02703 ]
 [-0.521316  0.241171  0.818576  0.125181]
 [ 0.566357  0.815306  0.120481 -0.252969]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.644673  0.523346 -0.557231 -3.02418 ]
 [-0.519154  0.235334  0.821643  0.125723]
 [ 0.561139  0.81898   0.119984 -0.249588]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.64803   0.519584 -0.556857 -3.02288 ]
 [-0.519491  0.233119  0.822062  0.125913]
 [ 0.556944  0.822002  0.118851 -0.248318]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.650056  0.514966 -0.558782 -3.02088 ]
 [-0.521534  0.232458  0.820954  0.127189]
 [ 0.552657  0.82509   0.117462 -0.245962]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.64677   0.512069 -0.56522  -3.0218  ]
 [-0.531476  0.228923  0.815554  0.127804]
 [ 0.547012  0.827877  0.124091 -0.243252]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.639735  0.

 76%|███████▌  | 6487/8560 [00:07<00:02, 929.65it/s]

614400
[[-0.241091  -0.229318   0.943021  -3.24334  ]
 [ 0.630043   0.702103   0.331809  -0.132416 ]
 [-0.738188   0.67414   -0.0247909 -0.147707 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.238328  -0.224341   0.944918  -3.23798  ]
 [ 0.633644   0.701422   0.326349  -0.137372 ]
 [-0.736      0.67652   -0.0250164 -0.14903  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.235461  -0.219574   0.946755  -3.23304  ]
 [ 0.63655    0.701279   0.320955  -0.139433 ]
 [-0.734413   0.67823   -0.0253537 -0.149818 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.234003  -0.217077   0.947692  -3.23045  ]
 [ 0.637979   0.701255   0.318157  -0.140236 ]
 [-0.733638   0.679058  -0.0256054 -0.149301 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.232699  -0.215486   0.948376  -3.22775  ]
 [ 0.640164   0.700165   0.316162  -0.143413 ]
 [-0.732149   0.680686  -0.0249815 -0.150342 ]
 [ 0.         0.

 78%|███████▊  | 6675/8560 [00:07<00:02, 929.51it/s]

BYTES 921600 614400
[[-0.945777 -0.106526  0.30685  -1.2681  ]
 [ 0.215323  0.50167   0.837832 -0.992437]
 [-0.243188  0.858475 -0.45153   0.658899]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.942495 -0.111123  0.315205 -1.26717 ]
 [ 0.216984  0.513875  0.82997  -1.00471 ]
 [-0.254205  0.850637 -0.460213  0.658767]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.941492 -0.112107  0.317843 -1.26724 ]
 [ 0.217761  0.517443  0.827546 -1.00983 ]
 [-0.25724   0.848342 -0.462756  0.658182]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.938796 -0.103952  0.328416 -1.26998 ]
 [ 0.227697  0.528146  0.818056 -1.02056 ]
 [-0.25849   0.842767 -0.472151  0.653966]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.936424 -0.100572  0.336149 -1.2705  ]
 [ 0.233478  0.536535  0.810936 -1.0267  ]
 [-0.261914  0.837863 -0.478943  0.652073]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.93246   -0

 80%|████████  | 6867/8560 [00:07<00:01, 938.64it/s]

[[-0.783897   0.305663  -0.54044   -1.23209  ]
 [-0.468859   0.279203   0.837983  -1.23976  ]
 [ 0.407033   0.910283  -0.0755535  1.11428  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.782787   0.307556  -0.540974  -1.23214  ]
 [-0.469625   0.278399   0.837822  -1.24325  ]
 [ 0.408284   0.909892  -0.0734913  1.11852  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.780774   0.30989   -0.542549  -1.23379  ]
 [-0.47163    0.277252   0.837076  -1.2498   ]
 [ 0.409825   0.90945   -0.0703179  1.1227   ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.778964  0.308497 -0.545934 -1.2324  ]
 [-0.47483   0.278462  0.834862 -1.25376 ]
 [ 0.409575  0.909554 -0.070428  1.12838 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.778109   0.308057  -0.5474    -1.23359  ]
 [-0.476782   0.277694   0.834005  -1.25651  ]
 [ 0.408931   0.909938  -0.0692004  1.13128  ]
 [ 0.         0.         0.         1. 

 82%|████████▏ | 7055/8560 [00:07<00:01, 923.00it/s]

[[-0.169814   0.16895   -0.970886  -2.53622  ]
 [-0.770608   0.591328   0.237685  -0.783422 ]
 [ 0.614269   0.788534   0.0297786  0.386299 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.165925   0.171975  -0.971027  -2.5252   ]
 [-0.766353   0.597215   0.236722  -0.789537 ]
 [ 0.620622   0.783428   0.0327003  0.390269 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.163828   0.173003  -0.971201  -2.51888  ]
 [-0.763879   0.600714   0.235863  -0.791658 ]
 [ 0.624218   0.780521   0.0337393  0.392115 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.16051    0.177201  -0.970998  -2.50616  ]
 [-0.759788   0.605771   0.236145  -0.797728 ]
 [ 0.630047   0.775656   0.0374031  0.397983 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.159013  0.179333 -0.970853 -2.49929 ]
 [-0.758399  0.607404  0.236414 -0.799183]
 [ 0.632096  0.773886  0.039421  0.402002]
 [ 0.        0.        0.        1.

 85%|████████▍ | 7248/8560 [00:08<00:01, 941.14it/s]

[[ 5.33501e-01  4.58377e-01 -7.10822e-01 -2.42352e+00]
 [-6.52978e-01  7.57375e-01 -1.68880e-03 -1.14984e+00]
 [ 5.37585e-01  4.65052e-01  7.03370e-01  9.50399e-01]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]
BYTES 921600 614400
[[ 0.52903     0.453458   -0.717289   -2.42509   ]
 [-0.654204    0.756305   -0.00437917 -1.15763   ]
 [ 0.540503    0.47157     0.696762    0.95279   ]
 [ 0.          0.          0.          1.        ]]
BYTES 921600 614400
[[ 0.528173   0.445021  -0.72318   -2.42911  ]
 [-0.656026   0.754594  -0.0147744 -1.1695   ]
 [ 0.539132   0.482228   0.690501   0.961948 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.531972   0.44297   -0.721653  -2.43303  ]
 [-0.655252   0.755159  -0.0194875 -1.1749   ]
 [ 0.53633    0.483232   0.69198    0.96407  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.539002   0.435452  -0.721012  -2.44225  ]
 [-0.650194   0.75927   -0.0275025 -1.18593  ]
 [ 0.535467   0.483621

 86%|████████▌ | 7343/8560 [00:08<00:01, 936.20it/s]

BYTES 921600 614400
[[ 0.959617   0.0275408 -0.279957  -1.674    ]
 [-0.159528   0.872975  -0.46094   -1.07676  ]
 [ 0.231701   0.486988   0.842115   0.673005 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.954948   0.0341767 -0.294798  -1.66369  ]
 [-0.172896   0.87143   -0.459039  -1.07918  ]
 [ 0.241207   0.489328   0.83808    0.673565 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.951771  0.045684 -0.303388 -1.65064 ]
 [-0.188775  0.866714 -0.461704 -1.07833 ]
 [ 0.241858  0.496709  0.833538  0.679983]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.952822   0.0600214 -0.297538  -1.63419  ]
 [-0.198148   0.865563  -0.459932  -1.08364  ]
 [ 0.229932   0.49719    0.83662    0.682562 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.953628   0.0630231 -0.294316  -1.62447  ]
 [-0.199564   0.864392  -0.461521  -1.08754  ]
 [ 0.225317   0.498854   0.836885   0.683632 ]
 [ 0.         0.   

 88%|████████▊ | 7536/8560 [00:08<00:01, 945.72it/s]

BYTES 921600 614400
[[ 0.881442   0.322842  -0.344722  -1.16254  ]
 [-0.348039   0.937403  -0.0120177 -1.12635  ]
 [ 0.319263   0.13057    0.938628   0.99134  ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.882321   0.319666  -0.345431  -1.16338  ]
 [-0.346843   0.937748  -0.0181232 -1.11997  ]
 [ 0.318134   0.135801   0.938269   0.982057 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.882865   0.315707  -0.347676  -1.1664   ]
 [-0.346872   0.937446  -0.0295751 -1.10887  ]
 [ 0.31659    0.14671    0.937148   0.963295 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.882866   0.315736  -0.347647  -1.16809  ]
 [-0.351132   0.935374  -0.0422008 -1.09009  ]
 [ 0.311855   0.159327   0.936675   0.947822 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.882474   0.315061  -0.349251  -1.16879  ]
 [-0.351987   0.934872  -0.0460345 -1.08473  ]
 [ 0.312001   0.163556   0.935898   0.939939 ]
 [ 

 90%|█████████ | 7729/8560 [00:08<00:00, 953.27it/s]

[[ 0.398463  -0.446266   0.801296  -1.85174  ]
 [ 0.651563   0.752604   0.0951435 -1.05099  ]
 [-0.645518   0.484183   0.590655   0.809735 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[ 0.393851 -0.45321   0.799676 -1.85238 ]
 [ 0.654497  0.749124  0.102211 -1.04381 ]
 [-0.64538   0.48313   0.591668  0.806033]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.391726 -0.456224  0.799006 -1.85305 ]
 [ 0.656477  0.747044  0.104705 -1.04249 ]
 [-0.644662  0.483514  0.592137  0.803429]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.388142 -0.462772  0.796987 -1.85287 ]
 [ 0.661771  0.74182   0.108449 -1.03527 ]
 [-0.641408  0.485329  0.594181  0.792913]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.38228  -0.466834  0.797451 -1.85463 ]
 [ 0.663879  0.73904   0.114392 -1.03155 ]
 [-0.64275   0.485681  0.592441  0.788505]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[ 0.379983 -0.4682

 93%|█████████▎| 7926/8560 [00:08<00:00, 965.32it/s]

BYTES 921600 614400
[[-0.701449 -0.153187  0.696062 -2.11857 ]
 [ 0.483958  0.614578  0.622959 -1.00691 ]
 [-0.523214  0.773839 -0.356959  0.56385 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.702203 -0.150318  0.695927 -2.1182  ]
 [ 0.484546  0.615274  0.621814 -1.00945 ]
 [-0.521656  0.773849 -0.359211  0.561913]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.704406 -0.144334  0.694967 -2.11884 ]
 [ 0.484189  0.618222  0.619162 -1.00913 ]
 [-0.51901   0.772637 -0.365595  0.565215]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.70525  -0.142402  0.694509 -2.11904 ]
 [ 0.48458   0.618241  0.618838 -1.0099  ]
 [-0.517498  0.772981 -0.367009  0.564485]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.705433 -0.140926  0.694625 -2.11999 ]
 [ 0.485115  0.618512  0.618148 -1.01034 ]
 [-0.516747  0.773035 -0.367953  0.563841]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.706791 -0.

 95%|█████████▍| 8118/8560 [00:08<00:00, 943.54it/s]

BYTES 921600 614400
[[-0.725015   0.337202  -0.60054   -2.37893  ]
 [-0.506879   0.329092   0.796726  -1.08645  ]
 [ 0.46629    0.882039  -0.0676757  0.919103 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.716081   0.34411   -0.607302  -2.37897  ]
 [-0.510938   0.334373   0.79192   -1.08091  ]
 [ 0.475573   0.877373  -0.0636193  0.913839 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.696415   0.354833  -0.623779  -2.37928  ]
 [-0.527039   0.337056   0.780143  -1.07116  ]
 [ 0.487069   0.872059  -0.0477191  0.897309 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.685793   0.361268  -0.631801  -2.38025  ]
 [-0.532087   0.34341    0.773921  -1.06722  ]
 [ 0.496559   0.866923  -0.0432819  0.888179 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.665984   0.367726  -0.649032  -2.37812  ]
 [-0.538621   0.364898   0.759432  -1.05872  ]
 [ 0.516093   0.855352  -0.0449507  0.876843 ]
 [ 

 97%|█████████▋| 8308/8560 [00:09<00:00, 941.33it/s]

[[-0.746827    0.337564   -0.572975   -2.41799   ]
 [-0.440097    0.395058    0.806377    0.00449882]
 [ 0.498562    0.854388   -0.146479   -0.261289  ]
 [ 0.          0.          0.          1.        ]]
BYTES 921600 614400
[[-0.746971  0.33345  -0.575192 -2.42608 ]
 [-0.443189  0.395163  0.80463   0.010116]
 [ 0.495598  0.855954 -0.147394 -0.268958]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.754727   0.319426  -0.573023  -2.44337  ]
 [-0.442705   0.396622   0.804179   0.0201067]
 [ 0.484149   0.860615  -0.157929  -0.280052 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.759128   0.313678  -0.570378  -2.45198  ]
 [-0.441542   0.3957     0.805272   0.0247288]
 [ 0.478294   0.86315   -0.161885  -0.288479 ]
 [ 0.         0.         0.         1.       ]]
BYTES 921600 614400
[[-0.767917   0.300531  -0.565672  -2.4712   ]
 [-0.438703   0.396718   0.806321   0.0326171]
 [ 0.466737   0.86735   -0.172803  -0.300723 ]
 [ 0.         0.       

 99%|█████████▉| 8498/8560 [00:09<00:00, 942.23it/s]

[[-0.880474 -0.318146  0.351495 -2.91062 ]
 [ 0.261531  0.29245   0.919823  0.118026]
 [-0.395432  0.901807 -0.17429  -0.346094]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.883371 -0.317708  0.344553 -2.91166 ]
 [ 0.254549  0.292045  0.921908  0.117824]
 [-0.393522  0.902093 -0.177112 -0.344922]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.886278 -0.315708  0.338879 -2.91323 ]
 [ 0.248806  0.2926    0.923299  0.117371]
 [-0.390649  0.902615 -0.180775 -0.34609 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.888005 -0.314231  0.335717 -2.913   ]
 [ 0.245108  0.294258  0.923761  0.116956]
 [-0.389062  0.902591 -0.184282 -0.345056]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.891912 -0.312236  0.327112 -2.91067 ]
 [ 0.236481  0.294521  0.925923  0.11572 ]
 [-0.385448  0.903198 -0.188849 -0.345043]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.894227 -0.309894  0.322993 -2.

100%|██████████| 8560/8560 [00:09<00:00, 907.38it/s]
C:\Users\unid0\AppData\Local\Temp/ipykernel_4052/632782350.py:121: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array(data[key], dtype=np.float).tofile(out)


BYTES 921600 614400
[[-0.925825 -0.201112  0.320002 -2.90804 ]
 [ 0.217643  0.408517  0.886423  0.233019]
 [-0.308997  0.890319 -0.334445 -0.52124 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.925601 -0.203134  0.319374 -2.9106  ]
 [ 0.215152  0.411842  0.885492  0.23408 ]
 [-0.311405  0.888326 -0.337496 -0.521906]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.925753 -0.203648  0.318605 -2.91191 ]
 [ 0.214159  0.41204   0.88564   0.234836]
 [-0.311637  0.888116 -0.337834 -0.521934]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.925797 -0.205104  0.31754  -2.91488 ]
 [ 0.212155  0.41333   0.885522  0.235185]
 [-0.312873  0.887181 -0.339146 -0.52474 ]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.925859 -0.206896  0.316195 -2.91496 ]
 [ 0.210132  0.413557  0.885898  0.235677]
 [-0.314053  0.886659 -0.33942  -0.525293]
 [ 0.        0.        0.        1.      ]]
BYTES 921600 614400
[[-0.925448 -0.

### Custom dataset

In [ ]:
from scipy.spatial.transform import Rotation as rot

def read_frames(folder, obj, light='ambient@best', num_frames=100):
    frames = {'m_colorCompressed': [], 'm_depthCompressed': [], 'm_cameraToWorld': [],
              'm_timeStampColor': [], 'm_timeStampDepth': [], 
              'm_colorSizeBytes': [], 'm_depthSizeBytes': []}
    frames['num_frames'] = num_frames
    folder_frames = folder + '/processed_scans/images/'
    for i in range(int(num_frames)):
        frames['m_colorCompressed'].append(read_image(folder + f'undist/{obj}/tis_right/rgb/{number:04d}.jpg'))
        frames['m_timeStampColor'].append(i)
        frames['m_depthCompressed'].append(read_image(folder + f'depthmaps/{obj}/stl@tis_right.undist/{number:04d}.png'))
        frames['m_timeStampDepth'].append(i)
        
        h, w, c = frames['m_colorCompressed'][-1].shape
        frames['m_colorSizeBytes'].append(h*w*c) # uint8 * h * w * c 
        h, w = frames['m_depthCompressed'][-1].shape
        frames['m_depthSizeBytes'].append(2*h*w) # uint16 * h * w
        
    with open(folder + '/calibration/undist_extrinsics/_calibration/tis_right.images.txt') as f:
        for line in f.readlines():
            parsed_line = line().split(' ')
            transform_matrix = np.ones((4, 4), dtype=np.float32)
            transform_matrix[:3, :3] = rot.from_quat(np.array(parsed_line[1:4], dtype=np.float32)).as_matrix()
            transform_matrix[:. -1] = np.array(parsed_line[4:], dtype=np.float32)
            
            frames['m_cameraToWorld'].append(transform_matrix)
            
    return frames

In [5]:
from PIL import Image

In [16]:
im = np.array(read_image('./0000.png'), dtype=np.uint16)

In [17]:
im.max(), im.min()

(255, 0)

In [1]:
from image_utils import unpack_float32

In [6]:
im_depth = unpack_float32(read_image('./0000.png'))

In [8]:
im_depth[np.isnan(im_depth)] = 0.0

In [9]:
im_depth.max()

0.718291